tasks:
  - init: git remote set-url origin git@github.com:dineshsurya4597/dineshsurya4597-testrepo1.git && sed "s/\r$//" commit-command.sh | bash && gp open README.md
vscode:
 extensions:
   - redhat.java
   - vscjava.vscode-java-debug
   - kyntrack.rev-test-run